import type { ToolDescriptor } from "@jeanbot/types";

export const createToolCatalog = (): ToolDescriptor[] => [
  {
    id: "filesystem.workspace.scan",
    name: "Workspace scanner",
    kind: "filesystem",
    description: "Inspect workspace directories and files.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["scan"],
    capabilityHints: ["planning", "filesystem", "reasoning", "orchestration"],
    tags: ["workspace", "inventory", "read-only"],
    risk: "low"
  },
  {
    id: "filesystem.file.read",
    name: "Workspace file reader",
    kind: "filesystem",
    description: "Read a file inside the workspace with path traversal protection.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["read"],
    capabilityHints: ["filesystem", "reasoning", "software-development"],
    tags: ["workspace", "files", "read-only"],
    risk: "low"
  },
  {
    id: "filesystem.file.write",
    name: "Workspace file writer",
    kind: "filesystem",
    description: "Write a file inside the workspace and checkpoint the previous version automatically.",
    permissions: ["write"],
    requiresApproval: false,
    supportedActions: ["write"],
    capabilityHints: ["filesystem", "software-development", "writing"],
    tags: ["workspace", "files", "checkpoint"],
    risk: "medium"
  },
  {
    id: "filesystem.file.delete",
    name: "Workspace file deleter",
    kind: "filesystem",
    description: "Delete a file or directory inside the workspace after an explicit confirmation flag.",
    permissions: ["write"],
    requiresApproval: true,
    supportedActions: ["delete"],
    capabilityHints: ["filesystem", "software-development", "security"],
    tags: ["workspace", "files", "delete"],
    risk: "high"
  },
  {
    id: "filesystem.checkpoint.create",
    name: "Checkpoint creator",
    kind: "filesystem",
    description: "Create a checkpoint manifest before risky changes.",
    permissions: ["write"],
    requiresApproval: false,
    supportedActions: ["create"],
    capabilityHints: ["filesystem", "software-development", "orchestration"],
    tags: ["checkpoint", "recovery", "safety"],
    risk: "medium"
  },
  {
    id: "filesystem.checkpoint.list",
    name: "Checkpoint list",
    kind: "filesystem",
    description: "List recorded file checkpoints for a workspace path.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["list"],
    capabilityHints: ["filesystem", "software-development", "project-management"],
    tags: ["checkpoint", "recovery", "history"],
    risk: "low"
  },
  {
    id: "filesystem.checkpoint.rollback",
    name: "Checkpoint rollback",
    kind: "filesystem",
    description: "Restore a file or directory from a previous checkpoint.",
    permissions: ["write"],
    requiresApproval: true,
    supportedActions: ["rollback"],
    capabilityHints: ["filesystem", "software-development", "security"],
    tags: ["checkpoint", "recovery", "restore"],
    risk: "high"
  },
  {
    id: "filesystem.workspace.context.update",
    name: "Workspace context updater",
    kind: "filesystem",
    description: "Update the persistent workspace context file used by JeanBot.",
    permissions: ["write"],
    requiresApproval: false,
    supportedActions: ["update"],
    capabilityHints: ["planning", "memory", "project-management"],
    tags: ["context", "workspace", "state"],
    risk: "medium"
  },
  {
    id: "filesystem.artifact.write",
    name: "Artifact writer",
    kind: "filesystem",
    description: "Persist structured mission artifacts into the workspace.",
    permissions: ["write"],
    requiresApproval: false,
    supportedActions: ["write"],
    capabilityHints: ["filesystem", "writing", "software-development"],
    tags: ["artifact", "report", "output"],
    risk: "medium"
  },
  {
    id: "filesystem.jean.read",
    name: "JEAN reader",
    kind: "filesystem",
    description: "Read the current JEAN instructions file for a workspace.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["read"],
    capabilityHints: ["reasoning", "planning", "memory"],
    tags: ["jean", "config", "prompting"],
    risk: "low"
  },
  {
    id: "terminal.command.run",
    name: "Terminal runner",
    kind: "terminal",
    description: "Run shell commands in the workspace.",
    permissions: ["execute"],
    requiresApproval: true,
    supportedActions: ["run"],
    capabilityHints: ["terminal", "software-development", "data-analysis", "security"],
    tags: ["shell", "exec", "foreground"],
    risk: "high"
  },
  {
    id: "terminal.command.background",
    name: "Background runner",
    kind: "terminal",
    description: "Run a long command as a background job.",
    permissions: ["execute"],
    requiresApproval: true,
    supportedActions: ["run-background"],
    capabilityHints: ["terminal", "automation", "software-development"],
    tags: ["shell", "background", "jobs"],
    risk: "high"
  },
  {
    id: "terminal.command.list",
    name: "Terminal execution list",
    kind: "terminal",
    description: "List recorded terminal executions.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["list"],
    capabilityHints: ["terminal", "automation", "security"],
    tags: ["shell", "history", "logs"],
    risk: "low"
  },
  {
    id: "terminal.command.get",
    name: "Terminal execution reader",
    kind: "terminal",
    description: "Read one recorded terminal execution.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["get"],
    capabilityHints: ["terminal", "automation", "security"],
    tags: ["shell", "history", "record"],
    risk: "low"
  },
  {
    id: "terminal.command.output",
    name: "Terminal output reader",
    kind: "terminal",
    description: "Read stdout and stderr for a past execution.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["output"],
    capabilityHints: ["terminal", "software-development", "security"],
    tags: ["shell", "stdout", "stderr"],
    risk: "low"
  },
  {
    id: "terminal.background.list",
    name: "Background job list",
    kind: "terminal",
    description: "List background shell jobs.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["list"],
    capabilityHints: ["terminal", "automation", "project-management"],
    tags: ["shell", "background", "jobs"],
    risk: "low"
  },
  {
    id: "terminal.watch.start",
    name: "Workspace watcher",
    kind: "terminal",
    description: "Start or reuse a filesystem watch on a workspace path.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["watch"],
    capabilityHints: ["automation", "software-development", "heartbeat"],
    tags: ["watch", "filesystem", "events"],
    risk: "medium"
  },
  {
    id: "terminal.watch.list",
    name: "Workspace watch list",
    kind: "terminal",
    description: "List active workspace watches.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["list"],
    capabilityHints: ["automation", "heartbeat"],
    tags: ["watch", "filesystem", "status"],
    risk: "low"
  },
  {
    id: "browser.session.navigate",
    name: "Browser navigator",
    kind: "browser",
    description: "Open or reuse a browser session and navigate to a URL.",
    permissions: ["navigate"],
    requiresApproval: false,
    supportedActions: ["navigate"],
    capabilityHints: ["browser", "research", "multimodality"],
    tags: ["web", "session", "navigation"],
    risk: "medium"
  },
  {
    id: "browser.session.click",
    name: "Browser clicker",
    kind: "browser",
    description: "Click within a browser session by selector or coordinates.",
    permissions: ["interact"],
    requiresApproval: false,
    supportedActions: ["click"],
    capabilityHints: ["browser", "research", "automation"],
    tags: ["web", "click", "interaction"],
    risk: "medium"
  },
  {
    id: "browser.session.fill",
    name: "Browser form filler",
    kind: "browser",
    description: "Fill a form field inside a browser session.",
    permissions: ["interact"],
    requiresApproval: false,
    supportedActions: ["fill"],
    capabilityHints: ["browser", "automation"],
    tags: ["web", "forms", "interaction"],
    risk: "medium"
  },
  {
    id: "browser.session.extract",
    name: "Browser extractor",
    kind: "browser",
    description: "Extract text, HTML, or links from the current page.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["extract"],
    capabilityHints: ["browser", "research", "learning"],
    tags: ["web", "scrape", "extract"],
    risk: "low"
  },
  {
    id: "browser.session.capture",
    name: "Browser capture",
    kind: "browser",
    description: "Capture the current page as a screenshot or text artifact.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["capture"],
    capabilityHints: ["browser", "research", "multimodality"],
    tags: ["web", "capture", "screenshot"],
    risk: "low"
  },
  {
    id: "browser.session.list",
    name: "Browser session list",
    kind: "browser",
    description: "List browser sessions for the current operator scope.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["list"],
    capabilityHints: ["browser", "project-management"],
    tags: ["web", "session", "status"],
    risk: "low"
  },
  {
    id: "browser.session.get",
    name: "Browser session reader",
    kind: "browser",
    description: "Read one browser session summary and recent state.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["get"],
    capabilityHints: ["browser", "research"],
    tags: ["web", "session", "details"],
    risk: "low"
  },
  {
    id: "browser.session.events",
    name: "Browser event reader",
    kind: "browser",
    description: "Read recorded events for a browser session.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["events"],
    capabilityHints: ["browser", "research", "security"],
    tags: ["web", "events", "audit"],
    risk: "low"
  },
  {
    id: "browser.session.close",
    name: "Browser session closer",
    kind: "browser",
    description: "Close a browser session and release the resources.",
    permissions: ["write"],
    requiresApproval: false,
    supportedActions: ["close"],
    capabilityHints: ["browser", "automation"],
    tags: ["web", "session", "cleanup"],
    risk: "medium"
  },
  {
    id: "search.query",
    name: "Search engine",
    kind: "search",
    description: "Search indexed or synthetic sources.",
    permissions: ["query"],
    requiresApproval: false,
    supportedActions: ["search"],
    capabilityHints: ["research", "learning", "reasoning"],
    tags: ["search", "citation", "discovery"],
    risk: "low"
  },
  {
    id: "memory.recall",
    name: "Memory recall",
    kind: "memory",
    description: "Recall stored memories for a workspace.",
    permissions: ["query"],
    requiresApproval: false,
    supportedActions: ["recall"],
    capabilityHints: ["memory", "reasoning", "planning"],
    tags: ["memory", "retrieve", "context"],
    risk: "low"
  },
  {
    id: "memory.remember",
    name: "Memory writer",
    kind: "memory",
    description: "Persist a new workspace memory.",
    permissions: ["write"],
    requiresApproval: false,
    supportedActions: ["remember"],
    capabilityHints: ["memory", "automation", "project-management"],
    tags: ["memory", "persist", "context"],
    risk: "medium"
  },
  {
    id: "memory.forget",
    name: "Memory remover",
    kind: "memory",
    description: "Delete a specific memory record.",
    permissions: ["write"],
    requiresApproval: true,
    supportedActions: ["forget"],
    capabilityHints: ["memory", "project-management"],
    tags: ["memory", "delete", "cleanup"],
    risk: "high"
  },
  {
    id: "memory.summary",
    name: "Memory summarizer",
    kind: "memory",
    description: "Summarize the current workspace memory state.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["summary"],
    capabilityHints: ["memory", "reasoning", "planning"],
    tags: ["memory", "summary", "context"],
    risk: "low"
  },
  {
    id: "knowledge.query",
    name: "Knowledge query",
    kind: "knowledge",
    description: "Query ingested workspace knowledge.",
    permissions: ["query"],
    requiresApproval: false,
    supportedActions: ["query"],
    capabilityHints: ["research", "learning", "reasoning"],
    tags: ["knowledge", "search", "documents"],
    risk: "low"
  },
  {
    id: "knowledge.document.ingest",
    name: "Knowledge document ingester",
    kind: "knowledge",
    description: "Store structured workspace knowledge for later retrieval.",
    permissions: ["write"],
    requiresApproval: false,
    supportedActions: ["ingest"],
    capabilityHints: ["learning", "automation", "research"],
    tags: ["knowledge", "ingest", "documents"],
    risk: "medium"
  },
  {
    id: "knowledge.list",
    name: "Knowledge document list",
    kind: "knowledge",
    description: "List knowledge documents for a workspace.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["list"],
    capabilityHints: ["project-management", "learning"],
    tags: ["knowledge", "documents", "inventory"],
    risk: "low"
  },
  {
    id: "knowledge.export",
    name: "Knowledge export",
    kind: "knowledge",
    description: "Export the workspace knowledge corpus.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["export"],
    capabilityHints: ["learning", "research"],
    tags: ["knowledge", "export", "backup"],
    risk: "medium"
  },
  {
    id: "knowledge.summary",
    name: "Knowledge summary",
    kind: "knowledge",
    description: "Summarize the current knowledge base coverage.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["summary"],
    capabilityHints: ["learning", "reasoning", "planning"],
    tags: ["knowledge", "summary", "inventory"],
    risk: "low"
  },
  {
    id: "policy.evaluate",
    name: "Policy evaluator",
    kind: "policy",
    description: "Evaluate the risk posture of a proposed tool action.",
    permissions: ["evaluate"],
    requiresApproval: false,
    supportedActions: ["evaluate"],
    capabilityHints: ["security", "orchestration", "planning"],
    tags: ["policy", "risk", "approval"],
    risk: "low"
  },
  {
    id: "audit.list",
    name: "Audit reader",
    kind: "audit",
    description: "Read audit events for an entity.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["list"],
    capabilityHints: ["security", "heartbeat", "project-management"],
    tags: ["audit", "events", "history"],
    risk: "low"
  },
  {
    id: "communication.message.draft",
    name: "Message drafter",
    kind: "communication",
    description: "Draft outbound communication.",
    permissions: ["draft"],
    requiresApproval: false,
    supportedActions: ["draft"],
    capabilityHints: ["communication", "writing", "project-management"],
    tags: ["message", "draft", "outbound"],
    risk: "medium"
  },
  {
    id: "communication.message.send",
    name: "Message sender",
    kind: "communication",
    description: "Deliver outbound communication through configured channels.",
    permissions: ["send"],
    requiresApproval: true,
    supportedActions: ["send"],
    capabilityHints: ["communication", "automation", "finance"],
    tags: ["message", "send", "outbound"],
    risk: "high"
  },
  {
    id: "communication.message.list",
    name: "Message list",
    kind: "communication",
    description: "List previously drafted or sent messages.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["list"],
    capabilityHints: ["communication", "project-management"],
    tags: ["message", "history", "status"],
    risk: "low"
  },
  {
    id: "automation.heartbeat.create",
    name: "Heartbeat creator",
    kind: "automation",
    description: "Create a new heartbeat automation.",
    permissions: ["write"],
    requiresApproval: false,
    supportedActions: ["create"],
    capabilityHints: ["automation", "heartbeat", "project-management"],
    tags: ["heartbeat", "automation", "schedule"],
    risk: "medium"
  },
  {
    id: "automation.heartbeat.get",
    name: "Heartbeat reader",
    kind: "automation",
    description: "Read a single heartbeat definition.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["get"],
    capabilityHints: ["automation", "heartbeat"],
    tags: ["heartbeat", "automation", "status"],
    risk: "low"
  },
  {
    id: "automation.heartbeat.list",
    name: "Heartbeat list",
    kind: "automation",
    description: "List workspace heartbeats.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["list"],
    capabilityHints: ["automation", "heartbeat", "project-management"],
    tags: ["heartbeat", "automation", "inventory"],
    risk: "low"
  },
  {
    id: "automation.heartbeat.trigger",
    name: "Heartbeat trigger",
    kind: "automation",
    description: "Trigger a heartbeat run manually.",
    permissions: ["execute"],
    requiresApproval: false,
    supportedActions: ["trigger"],
    capabilityHints: ["automation", "heartbeat", "project-management"],
    tags: ["heartbeat", "automation", "execute"],
    risk: "medium"
  },
  {
    id: "automation.heartbeat.history",
    name: "Heartbeat history",
    kind: "automation",
    description: "List execution history for a heartbeat.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["history"],
    capabilityHints: ["automation", "heartbeat", "project-management"],
    tags: ["heartbeat", "automation", "history"],
    risk: "low"
  },
  {
    id: "automation.heartbeat.summary",
    name: "Heartbeat summary",
    kind: "automation",
    description: "Summarize global heartbeat execution health.",
    permissions: ["read"],
    requiresApproval: false,
    supportedActions: ["summary"],
    capabilityHints: ["automation", "heartbeat", "project-management"],
    tags: ["heartbeat", "automation", "summary"],
    risk: "low"
  }
];
